local generator_families = {
	{
		id = "code_analyzer",
		registryId = "code-analyzer",
		tranche = "classic-six",
		rendererKey = "classic-six.code_analyzer",
		contextKey = "analysisFocus",
		contextValue = "diff-backed hotspot triage",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "data_processing",
		registryId = "data-processing",
		tranche = "classic-six",
		rendererKey = "classic-six.data_processing",
		contextKey = "dataWindow",
		contextValue = "windowed anomaly replay",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "jargon",
		registryId = "jargon",
		tranche = "classic-six",
		rendererKey = "classic-six.jargon",
		contextKey = "languagePolicy",
		contextValue = "audience-calibrated terminology",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "metrics",
		registryId = "metrics",
		tranche = "classic-six",
		rendererKey = "classic-six.metrics",
		contextKey = "signalBlend",
		contextValue = "lagging-leading signal blend",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "network_activity",
		registryId = "network-activity",
		tranche = "classic-six",
		rendererKey = "classic-six.network_activity",
		contextKey = "transportMix",
		contextValue = "transport correlation map",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "system_monitoring",
		registryId = "system-monitoring",
		tranche = "classic-six",
		rendererKey = "classic-six.system_monitoring",
		contextKey = "telemetryScope",
		contextValue = "telemetry saturation watch",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "agent_workflows",
		registryId = "agent-workflows",
		tranche = "modern-core",
		rendererKey = "modern-core.agent_workflows",
		contextKey = "coordinationMode",
		contextValue = "handoff-guarded orchestration",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "ai_inference_ops",
		registryId = "ai-inference-ops",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "policy-and-inference grouping",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "platform_engineering",
		registryId = "platform-engineering",
		tranche = "modern-core",
		rendererKey = "modern-core.platform_engineering",
		contextKey = "platformSurface",
		contextValue = "platform release surface",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "supply_chain_security",
		registryId = "supply-chain-security",
		tranche = "modern-core",
		rendererKey = "modern-core.supply_chain_security",
		contextKey = "supplyChainPosture",
		contextValue = "artifact trust posture",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "observability_ai_runtime",
		registryId = "observability-ai-runtime",
		tranche = "modern-core",
		rendererKey = "modern-core.observability_ai_runtime",
		contextKey = "runtimeSignals",
		contextValue = "runtime signal braid",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "delivery_preview_ops",
		registryId = "delivery-preview-ops",
		tranche = "modern-core",
		rendererKey = "modern-core.delivery_preview_ops",
		contextKey = "deliveryGuardrail",
		contextValue = "preview-safe deployment gate",
		rendererDetail = "dedicated first-push renderer",
	},
	{
		id = "evaluation_and_guardrails",
		registryId = "evaluation-and-guardrails",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "evaluation-and-policy grouping",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "knowledge_retrieval",
		registryId = "knowledge-retrieval",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "retrieval governance fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "edge_client_runtime",
		registryId = "edge-client-runtime",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "edge-runtime policy fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "identity_and_trust",
		registryId = "identity-and-trust",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "identity-trust governance fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "aibom_provenance",
		registryId = "aibom-provenance",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "aibom provenance fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "agent_boundary_security",
		registryId = "agent-boundary-security",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "agent boundary fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "embedded_agentic_pipeline",
		registryId = "embedded-agentic-pipeline",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "embedded pipeline fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "data_governance_compliance",
		registryId = "data-governance-compliance",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "data compliance fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "finops_capacity",
		registryId = "finops-capacity",
		tranche = "ai-governance",
		rendererKey = "fallback.ai_governance",
		contextKey = "governanceLens",
		contextValue = "finops governance fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "blockchain_protocol_ops",
		registryId = "blockchain-protocol-ops",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "protocol security fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "cross_chain_interop",
		registryId = "cross-chain-interop",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "cross-chain interop fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "proof_and_sequencer_ops",
		registryId = "proof-and-sequencer-ops",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "proof and sequencer fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "hybrid_runtime_ops",
		registryId = "hybrid-runtime-ops",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "hybrid runtime fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "capacity_cost_controller",
		registryId = "capacity-cost-controller",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "capacity-cost fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "batch_execution_tuner",
		registryId = "batch-execution-tuner",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "batch tuning fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "compiler_maintainer",
		registryId = "compiler-maintainer",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "compiler maintenance fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "interop_adapter_engineer",
		registryId = "interop-adapter-engineer",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "interop adapter fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "preflight_capacity_planner",
		registryId = "preflight-capacity-planner",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "preflight capacity fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "simulator_performance_engineer",
		registryId = "simulator-performance-engineer",
		tranche = "security-blockchain",
		rendererKey = "fallback.security_blockchain",
		contextKey = "protocolRisk",
		contextValue = "simulator performance fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "fhir_profile_generator",
		registryId = "fhir-profile-generator",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "fhir profile fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "smart_launch_oauth",
		registryId = "smart-launch-oauth",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "smart launch fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "bulk_fhir_population_ops",
		registryId = "bulk-fhir-population-ops",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "bulk fhir fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "hl7v2_feed_ops",
		registryId = "hl7v2-feed-ops",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "hl7v2 feed fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "clinical_workflow_events",
		registryId = "clinical-workflow-events",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "clinical workflow fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "dicomweb_imaging_ops",
		registryId = "dicomweb-imaging-ops",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "dicomweb imaging fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "openehr_semantic_record_ops",
		registryId = "openehr-semantic-record-ops",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "openehr semantic fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "device_telemetry_clinical",
		registryId = "device-telemetry-clinical",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "clinical telemetry fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "emr_vendor_adapter",
		registryId = "emr-vendor-adapter",
		tranche = "health-protocol",
		rendererKey = "fallback.health_protocol",
		contextKey = "clinicalInterop",
		contextValue = "emr adapter fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "ocpp_chargepoint_ops",
		registryId = "ocpp-chargepoint-ops",
		tranche = "overlay-quantum",
		rendererKey = "fallback.overlay_quantum",
		contextKey = "meshSurface",
		contextValue = "chargepoint overlay fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "ocpi_roaming_ops",
		registryId = "ocpi-roaming-ops",
		tranche = "overlay-quantum",
		rendererKey = "fallback.overlay_quantum",
		contextKey = "meshSurface",
		contextValue = "roaming overlay fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "mcp_a2a_ops",
		registryId = "mcp-a2a-ops",
		tranche = "overlay-quantum",
		rendererKey = "fallback.overlay_quantum",
		contextKey = "meshSurface",
		contextValue = "agent-to-agent fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "streaming_bus_ops",
		registryId = "streaming-bus-ops",
		tranche = "overlay-quantum",
		rendererKey = "fallback.overlay_quantum",
		contextKey = "meshSurface",
		contextValue = "streaming bus fallback",
		rendererDetail = "grouped fallback renderer",
	},
	{
		id = "service_mesh_rpc_ops",
		registryId = "service-mesh-rpc-ops",
		tranche = "overlay-quantum",
		rendererKey = "fallback.overlay_quantum",
		contextKey = "meshSurface",
		contextValue = "service mesh fallback",
		rendererDetail = "grouped fallback renderer",
	},
}

local by_id = {}
for _, family in ipairs(generator_families) do
	by_id[family.id] = family
end

local M = {
	complexities = { "low", "medium", "high", "extreme" },
	dev_types = {
		"backend",
		"frontend",
		"fullstack",
		"data_science",
		"dev_ops",
		"blockchain",
		"machine_learning",
		"systems_programming",
		"game_development",
		"security",
	},
	experimental_flags = {
		"experimental-provider",
		"experimental-mode",
		"experimental-profile",
		"experimental-prompt-asset",
		"experimental-prompt-version",
		"experimental-personalization-profile",
		"experimental-model",
		"experimental-base-url",
		"experimental-session-file",
		"experimental-store",
		"experimental-bootstrap-command",
		"experimental-disable-cache",
	},
	experimental_modes = { "prompt-versioned", "personalized", "consumer-session" },
	experimental_providers = {
		"local-demo",
		"openai-compatible",
		"anthropic",
		"openai-consumer",
		"claude-consumer",
	},
	flags = {
		"alerts",
		"project",
		"minimal",
		"team",
		"framework",
		"seed",
		"output-format",
		"no-color",
		"trace",
		"list-values",
		"focus-family",
		"experimental-provider",
		"experimental-mode",
		"experimental-profile",
		"experimental-prompt-asset",
		"experimental-prompt-version",
		"experimental-personalization-profile",
		"experimental-model",
		"experimental-base-url",
		"experimental-session-file",
		"experimental-store",
		"experimental-bootstrap-command",
		"experimental-disable-cache",
	},
	generator_families = generator_families,
	jargon_levels = { "low", "medium", "high", "extreme" },
	output_formats = { "text", "json" },
	personalization_profiles = { "local-operator" },
	prompt_assets = { "stakeholder-live-brief", "consumer-replay-brief" },
}

function M.find_family(id)
	return by_id[id]
end

return M
